### ISSUE TITLE
Proximity mines cannot be picked up.

### ISSUE THREAD

**Issue by mechanator** [argonatorUberTF/Uber-Team-Fortress#10]
K3vin found that prox mines can't be disarmed and picked up for re-use as soldier class.
Attempting a fix uncovered a loop issue in weapons.pqc
The real fix is fixing the impulse loop and tracking which prox mine belongs to which player or team number. 
On attempted to fix it crashes the server with infinite loop errors. 
Likely require fixing the weapon select in combination with drop3 and the loop it runs with impulses and deadimpulses.

**Comment by mechanator** [comment]
This might be a problem with the fact that the prox mine deploy/disarm code is different than MegaTF Classics, and was changed somehow along the way after 2009-2015.  So this branch of mess needs to be addressed along with the weapon select and  special weapons. Perhaps a different control mechanism to be bound for more weapons as dreamed of by the devs eventually.

**Comment by argonatorUberTF** [comment]
rolled back weapons.pqc to the original I had and updated any changes I made carefully to make sure the prox mine can be disarmed and picked up.
