### ISSUE TITLE
cmd teleme doesn't work.

### ISSUE THREAD

**Issue by mechanator** [argonatorUberTF/Uber-Team-Fortress#11]
SharkCK reported that "cmd teleme" was missing. 
It never worked on Mega TF COOP and was originally only on Prozac Ratbert COOP. 
However, the cmd telem does work and will be modified to take the player to the monster's location and placed above instead of within the monster. Sometimes you are out of ammo , grenades, or cans of pork and beans to explode your way out. 
So.. this issue is hanging open until "cmd telem" is changed a bit. 
However, if one ends a map with 15 or less monsters in the map or stuck outside of the map you can still get the bonus EXP or flawless/survival mode bonus.

**Comment by argonatorUberTF** [comment]
Fixed cmd telem to teleport the player to above the monster instead of in the center.
