### ISSUE TITLE
rogue, flawed invisbl.mdl in progs directory crashes linux ezquake

### ISSUE THREAD

**Issue by argonatorUberTF** [argonatorUberTF/Uber-Team-Fortress#9]
I was looking at issues on github for ezquake.  One caught my eye.
https://github.com/ezQuake/ezquake-source/issues/415
Some nquake and ezquake clients crash when connecting to the coop server. It seems the invisibl.mdl is corrupt.
There is  duplicate invisibl.mdl in the fortress/progs on both the coop and the uber tf  servers. Remove it. 
invisbl.mdl is already in pak1.pak stored there, that's the one to be used. By default. 
So that's a bug solved.
Probably might show up in the classics mod also.
Removed inivsible.mdl from the directory tree for /fortress/progs for client and server to use the correct model in pak1.pak

**Comment by argonatorUberTF** [comment]
Testing

**Comment by argonatorUberTF** [comment]
Works with windows clients, nquake,ezquake. Testing Linux versions
.

**Comment by mechanator** [comment]
closed
